### ISSUE TITLE
Surprising light mode behavior on first load

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/explorer#194]
**Describe the bug**

When I first load the explorer, it's already in light mode. Yet the footer says "Light mode" (surprise 1)
When I click on "Light mode", the explorer actually goes into "Dark mode" (surprise 2)
When I click on "Light mode" again, the explorer goes back to light mode, and the text says "Dark mode" (as it should, but it's inconsistent with behavior in surprise 1)

**To Reproduce**
1. Open explorer
2. Click on light mode (explorer turns dark)
3. Click on light mode again (explorer turns light)

**Expected behavior**
See above

**Screenshots**

![Screenshot 2020-06-22 22 07 00](https://user-images.githubusercontent.com/15990/85352922-1b766880-b4d5-11ea-8a88-46f6edac28b1.png)
![Screenshot 2020-06-22 22 07 15](https://user-images.githubusercontent.com/15990/85352921-1addd200-b4d5-11ea-9c4f-8c088614f911.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Comment by aulneau** [comment]
Interesting, what mode is your system in? (light/dark?)

**Comment by diwakergupta** [comment]
System as in the default mode on my Mac? It's light. FWIW I don't think it's OS dependent: I can reliably reproduce it on all browsers and all operating systems. Seems like `colorMode` might not get be getting initialized correctly in some instances?

https://github.com/blockstack/explorer/blob/00ce7785f48ef4b97c7edb7c2f87851ea7ebdca8/src/components/footer.tsx#L22

Another data point: if I simply reload Explorer without doing anything else, the "Light mode" in the footer switches to "Dark mode" upon reload, further reinforcing my hypothesis.

**Comment by aulneau** [comment]
Yep -- forgot to initialize the value for use with the mode button, much of this implementation relies on css media queries. This should be fixed with https://github.com/blockstack/explorer/pull/190/commits/c716c1072723d82dfb1a808767eabe35bf068c59#diff-f72c052bf7061916729a13a36a5bd97bR174-R179 which you can test here: https://explorer-irmefy124.vercel.app/

**Comment by diwakergupta** [comment]
Thanks, I can confirm it works for me. Though there's a visible delay -- the page renders with "Light mode" in the footer and then 1-2 seconds later the text changes to "Dark mode".

**Comment by aulneau** [comment]
Yep -- that it just the nature of the situation unfortunately. Due to the application being rendered on the server first, there is no way to get any kind of information related to a media query in that env. I have opted to only show the switcher once the client has hydrated and set the value of the color mode. So rather than showing the wrong value, we'll show nothing until it has time to set itself. Once toggled, the value will be available on the server because we're saving it in a cookie. If you're interested, there are some good articles about this -> [here](https://brianlovin.com/overthought/adding-dark-mode-with-next-js) and [here](https://joshwcomeau.com/gatsby/dark-mode/).
