### ISSUE TITLE
Add support for microblocks

### ISSUE THREAD

**Issue by markmhx** [blockstack/explorer#430]
We should support microblocks in the UX as they pertain to ending and confirmed transactions.

**Comment by GAD2511** [comment]
All my focus on microblocks for UX and for stacks improvements

**Comment by jasperjansz** [comment]
These might need to be split into discrete tasks.

**Home**: https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Explorer?node-id=2847%3A2321
- The list of confirmed transactions is segmented by 'in microblock' and 'in anchor block'. There is no space to explain in line, so the info icons at either label should link to the docs which explain the difference, anchored to the respective section. 
- Blocks show microblocks and anchor blocks

**Transactions overview** https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Explorer?node-id=2847%3A1735
- Same as the list of transactions on the home page
- You can see the interaction for the headers here: https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Explorer?node-id=2847%3A238
- Pending transaction: https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Explorer?node-id=2847%3A449

**Blocks overview**: https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Explorer?node-id=2847%3A1477
- Same as on homepage

**Individual transactions**
- Update to the title to show the state (pending, in microblock, or in anchor block): https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Explorer?node-id=2847%3A1198
- Add component to show historical state changes: https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Explorer?node-id=2847%3A878 (this will be used in the transactions details view on the web wallet too)
- If included in anchor block, show number of anchor block confirmations since: https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Explorer?node-id=2847%3A878

**Block**:
https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Explorer?node-id=2390%3A15241

**Comment by pxydn** [comment]
these are so cool @jasperjansz handsdown. good job 👍 looking forward to testing these out

**Comment by kyranjamie** [comment]
Closing in favour of said discrete tasks #453 #454 #455
