### ISSUE TITLE
Pending contract deploy page is not to be found

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/explorer#495]
Testnet environment
PR:https://github.com/blockstack/explorer/pull/493
URL:https://explorer-git-feat-microblocks-final-blockstack.vercel.app/transactions?chain=testnet

User deployed contact via sandbox on Explorer and the action steps as below:
-User noticed the contract is in pending transaction(accurate)
-User select the pending transaction and is directed to a page where its not found
-After few minutes however,user is able to select the same pending transaction and able to view the pending explorer page

Attaching the video for perusal

https://user-images.githubusercontent.com/38872890/127391340-1199bcc4-626e-4fe0-9429-5734be01499d.mov

**Comment by aulneau** [comment]
Thanks for this, very helpful @Eshwari007 !

fixed by: https://github.com/blockstack/explorer/commit/5637f28dc4142cb27e883c8852c052244559f312

This error is unique to contract deploys -- we're fetching data from an endpoint `extended/v1/contract/` that doesn't work until the contract is in microblock or anchor block.

**Comment by Eshwari007** [comment]
Test passing now-Moving it to Done
